exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

preprocessor:
  name: base

pipeline:
  name: train

trainer:
  name: oco
  trainer_args:
    recon_loss_weight: 1.0

evaluator:
  name: base

optimizer:
  name: adamw
  num_epochs: 20
  lr: 0.0004
  final_lr: 0.00004
  weight_decay: 0.05
  warmup_epochs: 1

recorder:
  name: base
  save_all_models: False
